apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      # --- จุดสำคัญ: ต้องอยู่ตรงนี้ ---
      imagePullSecrets:
      - name: acr-secret
      # ---------------------------
      containers:
      - name: my-api
        image: teeraregistry77.azurecr.io/my-secure-api:latest  # << เช็ค Tag จากข้อ 1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"