name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ] # ทำงานเมื่อมีการ Push ขึ้นกิ่ง main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Security Scan (SAST)
      run: |
        pip install bandit
        bandit -r app.py # สแกนไฟล์ app.py ของเรา

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push to ACR
      run: |
        az acr login --name teeraregistry77
        docker build -t teeraregistry77.azurecr.io/my-secure-api:${{ github.sha }} .
        docker push teeraregistry77.azurecr.io/my-secure-api:${{ github.sha }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: MyDevSecOpsRG
        cluster-name: MyDevSecOpsCluster

    - name: Deploy to Kubernetes
      run: |
        # เปลี่ยนชื่อ image ใน deployment.yaml ให้เป็นตัวใหม่ล่าสุดที่มีเลข SHA ต่อท้าย
        sed -i "s|image:.*|image: teeraregistry77.azurecr.io/my-secure-api:${{ github.sha }}|g" deployment.yaml
        kubectl apply -f deployment.yaml